#!/bin/bash

# en_US ISO-8859-1
# en_US.UTF-8 UTF-8
# zh_CN GB18030
# zh_CN.GBK GBK
# zh_CN.GB2312 GB2312
# zh_CN.UTF-8 UTF-8
#
# surround above with the command
# :%s/\(.*\)/echo \"\1\" >> \/etc\/locale.gen/g

echo "en_US ISO-8859-1" >> /etc/locale.gen
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
echo "zh_CN GB18030" >> /etc/locale.gen
echo "zh_CN.GBK GBK" >> /etc/locale.gen
echo "zh_CN.GB2312 GB2312" >> /etc/locale.gen
echo "zh_CN.UTF-8 UTF-8" >> /etc/locale.gen
